name: Java CI with Maven

on: [push, pull_request]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven
      - name: CLOC
        run: |
          sudo apt-get install cloc -y
          cloc src
      - name: Build and run tests
        run: mvn --batch-mode --fail-at-end package
      - name: Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1.4.0
        with:
          report_paths: 'target/surefire-reports/TEST-*.xml'
      - name: Upload Report
        uses: 'actions/upload-artifact@v3.1.2'
        with:
          name: report.xml
          path: target/site/jacoco/jacoco.xml
